apiVersion: v1
kind: ReplicationController
metadata:
  name: gearmand
  labels:
    app: gearmand
spec:
  replicas: 1
  selector:
    app: gearmand
  template:
    metadata:
      labels:
        app: gearmand
    spec:
      containers:
      - image: pataquets/gearmand
        name: gearmand
        ports:
        - containerPort: 4730
        imagePullPolicy: Always
