  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: zoneminder-config
  spec:
    capacity:
      storage: 500Mi
    accessModes:
      - ReadWriteOnce
    nfs:
      path: /mnt/fileserv/kubernetes/zoneminder
      server: 10.0.1.14
