apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateapi
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - gateapi.burntsheep.com
    secretName: gateapi-cert
  rules:
  - host: gateapi.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gateapi
          servicePort: 80
