apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-repo-v0
  namespace: kube-system
  labels:
    k8s-app: docker-repo
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: docker-repo
    version: v0
  template:
    metadata:
      labels:
        k8s-app: docker-repo
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - name: docker-configs
          mountPath: /docker_configs
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: docker-repo
      - name: docker-configs
        persistentVolumeClaim:
          claimName: docker-configs
