apiVersion: v1
kind: Service
metadata:
  name: docker-repo
  namespace: kube-system
  labels:
    k8s-app: docker-repo
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "docker-repo"
spec:
  selector:
    k8s-app: docker-repo
  ports:
  - name: registry
    port: 5000
    protocol: TCP
  externalIPs: ["10.0.1.19","10.0.1.20","10.0.1.21","10.0.1.22","10.0.1.23"]
