  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: observium-config
  spec:
    capacity:
      storage: 100Mi
    accessModes:
      - ReadWriteOnce
    nfs:
      path: /mnt/fileserv/kubernetes/observium/config
      server: 10.0.1.14
