apiVersion: v1
kind: ReplicationController
metadata:
  name: bf1942-v0
  labels:
    app: bf1942
    version: v0
spec:
  replicas: 1
  selector:
    app: bf1942
    version: v0
  template:
    metadata:
      labels:
        app: bf1942
        version: v0
    spec:
      containers:
      - name: bf1942
        image: inanimate/battlefield1942
        resources:
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: bf1942-store
          mountPath: /srv/bf1942/mods/bf1942/settings
        ports:
        - containerPort: 14567
          protocol: UDP
          name: bf1942-main
        imagePullPolicy: Always
      volumes:
      - name: bf1942-store
        persistentVolumeClaim:
          claimName: bf1942
