apiVersion: v1
kind: ReplicationController
metadata:
  name: insurgency-v0
  labels:
    app: insurgency
    version: v0
spec:
  replicas: 1
  selector:
    app: insurgency
    version: v0
  template:
    metadata:
      labels:
        app: insurgency
        version: v0
    spec:
      containers:
      - name: hlstatsx-scr
        image: 10.0.1.14:5000/hlstatsx_scripts
        resources:
          limits:
            cpu: 0.5
        ports:
        - containerPort: 27500
          name: hlstatsx-scr
          protocol: UDP
        imagePullPolicy: Always
      - name: insurgency
        image: 10.0.1.14:5000/insurgency_dedicated
        resources:
          limits:
            cpu: 3
            memory: 2Gi
        volumeMounts:
        - name: insurgency-store
          mountPath: /insurgency
        ports:
        - containerPort: 27015
          name: insurg-main
        - containerPort: 27015
          name: insurg-main-udp
          protocol: UDP
        - containerPort: 27005
          name: insurg-05
          protocol: UDP
        - containerPort: 27020
          name: insurg-20
          protocol: UDP
        imagePullPolicy: Always
      volumes:
      - name: insurgency-store
        persistentVolumeClaim:
          claimName: insurgency
