apiVersion: v1
kind: ReplicationController
metadata:
  name: insurgency-v0
  labels:
    app: insurgency
    version: v0
spec:
  replicas: 1
  selector:
    app: insurgency
    version: v0
  template:
    metadata:
      labels:
        app: insurgency
        version: v0
    spec:
      containers:
      - name: insurgency
        image: localhost:5000/insurgency_dedicated
        resources:
          limits:
            cpu: 3
            memory: 2Gi
        volumeMounts:
        - name: insurgency-store
          mountPath: /srv/insurgency_data
        ports:
        - containerPort: 27015
          name: insurgency-main
        - containerPort: 27015
          name: insurgency-main-udp
          protocol: UDP
        - containerPort: 27005
          name: insurgency-05
          protocol: UDP
        - containerPort: 27020
          name: insurgency-20
          protocol: UDP
      volumes:
      - name: insurgency-store
        persistentVolumeClaim:
          claimName: insurgency
