apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: baby
spec:
  tls:
  - hosts:
    - baby.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: baby.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: baby
          servicePort: 80
      - path: /.well-known
        backend:
          serviceName: letsencrypt
          servicePort: 80
