apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fileserv
spec:
  rules:
  - host: fileserv.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fileserv
          servicePort: 80
