apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fileserv
spec:
  tls:
  - hosts:
    - fileserv.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: fileserv.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fileserv
          servicePort: 80
      - path: /.well-known
        backend:
          serviceName: letsencrypt
          servicePort: 80
