apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openhab
spec:
  tls:
  - hosts:
    - openhab.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: openhab.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: openhab
          servicePort: 80
