apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonaar
spec:
  rules:
  - host: sonaar.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonaar
          servicePort: 80
