apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonaar
spec:
  tls:
  - hosts:
    - sonaar.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: sonaar.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonaar
          servicePort: 80
      - path: /.well-known
        backend:
          serviceName: letsencrypt
          servicePort: 80
