apiVersion: v1
kind: Service
metadata:
  name: hurtworld
  labels:
    k8s-app: hurtworld
    kubernetes.io/name: "hurtworld"
spec:
  selector:
    k8s-app: hurtworld
  ports:
  - name: hw-client
    port: 12881
    protocol: UDP
  - name: hw-main
    port: 12871
    protocol: UDP
  externalIPs: ["10.0.1.19", "10.0.1.20", "10.0.1.21", "10.0.1.22", "10.0.1.23"]
