  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: docker-configs
    namespace: kube-system
  spec:
    capacity:
      storage: 500Gi
    accessModes:
      - ReadWriteMany
    nfs:
      path: /mnt/fileserv/docker_configs
      server: 10.0.1.14
