apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
spec:
  tls:
  - hosts:
    - jenkins.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: jenkins.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80
      - path: /.well-known
        backend:
          serviceName: letsencrypt
          servicePort: 80
