apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hlstatsx
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - stats.burntsheep.com
    secretName: stats-cert
  rules:
  - host: stats.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hlstatsx
          servicePort: 80
