apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hlstatsx
spec:
  rules:
  - host: stats.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hlstatsx
          servicePort: 80
