apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gate
  namespace: default
spec:
  tls:
  - hosts:
    - gate.burntsheep.com
    secretName: nginx-certs
  rules:
  - host: gate.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gate
          servicePort: 80
      - path: /.well-known
        backend:
          serviceName: letsencrypt
          servicePort: 80
