apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gate
spec:
  rules:
  - host: gate.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gate
          servicePort: 80
