apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gate
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - gate.burntsheep.com
    secretName: gate-cert
  rules:
  - host: gate.burntsheep.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gate
          servicePort: 80
