apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kube-system
  labels:
    k8s-app: mysql
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "mysql"
spec:
  selector:
    k8s-app: mysql
  ports:
  - name: mysql
    port: 3306
  externalIPs: ["10.0.1.19","10.0.1.20","10.0.1.21","10.0.1.22","10.0.1.23"]
